#!/bin/bash
# clear: if you want to clear the above info in the command
echo "copying the nignix folders and files..."
mkdir /etc/nginx/sites-available
mkdir /etc/nginx/sites-enabled
cp -pr /fruit/src/ngnix/* /etc/nginx
# Create a symbolic link between sites-available and sites-enabled
ln -s /etc/nginx/sites-available/fruit.com.conf /etc/nginx/sites-enabled/fruit.com.conf
service nginx restart